name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run CI
        run: npm run ci

      - name: Install in new next.js project # make sure it can be installed in a new project
        run: |
          npx create-next-app@latest test-app --typescript --eslint --tailwind --app --src-dir --yes
          cd test-app
          npm i use-resetable-action-state
